server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

  freemarker:
    enabled: true

spring.mvc.view.prefix: classpath:/templates/
spring.mvc.view.suffix: .ftl

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    # Render genera la URL p√∫blica del servicio en esta variable
    hostname: ${RENDER_EXTERNAL_URL:eurekaserver-dg33.onrender.com}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
